apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anelia
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CSS-BB/anelia
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: nula-tri-osmici-maika-ti-po-cici
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true