apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demonstrationvideo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/css-bb/demonstrationvideo
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: demonstration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true