apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: presentation-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/css-bb/presentation-demo
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: nula-tri-osmici-maika-ti-po-cici
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true